"""
Enrich PDF figure crops with Alfred Vision descriptions.

Reads pdf_image_tasks_*.jsonl files (generated by pdf_figure_service during ingestion),
sends each cropped figure to Alfred Vision API, and saves descriptions to
data/pdf_image_descriptions.json.

After running this, re-running fetch_files (or just the enrichment step) will
inject the descriptions into the PDF text content via [FIGURE_DESCRIPTIONS] blocks.

Usage:
    python pipeline_Automation/alfred/enrich_pdf_figures_with_alfred.py
    python pipeline_Automation/alfred/enrich_pdf_figures_with_alfred.py --repo STM32CubeH7
    python pipeline_Automation/alfred/enrich_pdf_figures_with_alfred.py --max-figures 50 --use-proxy

Requires: requests, Pillow (for format conversion if needed)
"""

import argparse
import base64
import hashlib
import io
import json
import mimetypes
import os
import random
import time
from pathlib import Path
from typing import Any

import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

try:
    from PIL import Image
except ImportError:
    Image = None

# --- Project paths ---
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
DESCRIPTIONS_FILE = DATA_DIR / "pdf_image_descriptions.json"

# --- Alfred Vision API credentials ---
CLIENT_APP_NAME = os.getenv("ALFRED_CLIENT_APP_NAME", "mdrf_stgithub_analyzer_client").strip()
API_KEY = (
    os.getenv("ST_CHATGPT_API_KEY")
    or os.getenv("ST_AI_BRIDGE_API_KEY")
    or os.getenv("ST_API_KEY")
    or ""
).strip()
API_URL = os.getenv("ALFRED_API_URL", "https://api-ai-bridge.st.com/chatgpt/api/client-apps").strip()
CHAT_SERVICE = "chat"
DEFAULT_PERSONA = "st_copilot"

PROXIES = {
    "http": "http://185.46.212.88:80",
    "https": "http://185.46.212.88:80",
}

SYSTEM_PROMPT = (
    "You analyze technical figures and diagrams from STM32Cube PDF documentation. "
    "Return plain text only, no markdown, in this exact format: "
    "DESCRIPTION: <technical description of the diagram, blocks, arrows, interfaces>\n"
    "LABELS: <comma-separated list of all readable labels/text in the figure>"
)


def generate_token(timestamp: int, nonce: int) -> str:
    """Compute the SHA1 auth token expected by the Alfred chat/vision API for one request."""
    data_string = f"{CLIENT_APP_NAME}_{CHAT_SERVICE}_{API_KEY}_{timestamp}_{nonce}"
    return hashlib.sha1(data_string.encode("utf-8")).hexdigest()


def load_image_as_data_url(image_path: Path, max_bytes: int = 6_000_000) -> str:
    """Read a local PNG/JPG figure and convert to a data URL for Alfred."""
    if not image_path.exists():
        raise FileNotFoundError(f"Figure file not found: {image_path}")

    image_bytes = image_path.read_bytes()

    mime_type, _ = mimetypes.guess_type(str(image_path))
    if not mime_type or not mime_type.startswith("image/"):
        mime_type = "image/png"

    # Alfred only accepts image/png or image/jpg
    if mime_type == "image/jpeg":
        mime_type = "image/jpg"

    if mime_type not in ("image/png", "image/jpg"):
        if Image is None:
            raise ValueError(f"Cannot convert {mime_type} to PNG (Pillow not installed)")
        img = Image.open(io.BytesIO(image_bytes))
        buf = io.BytesIO()
        img.convert("RGB").save(buf, format="PNG")
        image_bytes = buf.getvalue()
        mime_type = "image/png"

    if len(image_bytes) > max_bytes:
        raise ValueError(f"Image too large ({len(image_bytes)} bytes): {image_path}")

    encoded = base64.b64encode(image_bytes).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def extract_text_from_response(response_json: dict) -> str | None:
    """Best-effort extraction of the completion text from an Alfred API response.

    Checks several known response shapes (``completion``, ``text``/``content``/
    ``message``/``answer``, OpenAI-style ``choices``) since the exact shape can
    vary by backend/persona.
    """
    if not isinstance(response_json, dict):
        return None

    completion = response_json.get("completion")
    if isinstance(completion, str) and completion.strip():
        return completion.strip()

    for key in ("text", "content", "message", "answer"):
        val = response_json.get(key)
        if isinstance(val, str) and val.strip():
            return val.strip()

    choices = response_json.get("choices", [])
    if choices and isinstance(choices[0], dict):
        msg = choices[0].get("message", {})
        if isinstance(msg, dict) and msg.get("content"):
            return msg["content"].strip()

    return None


def call_alfred_for_figure(
    data_url: str,
    prompt: str,
    page_context: str,
    use_proxy: bool = False,
    max_retries: int = 3,
    timeout: int = 120,
) -> str:
    """Send a figure crop to Alfred Vision and return the description."""
    if not CLIENT_APP_NAME:
        raise ValueError("Missing Alfred client app name. Set ALFRED_CLIENT_APP_NAME.")
    if not API_KEY:
        raise ValueError("Missing Alfred API key. Set ST_CHATGPT_API_KEY (or ST_AI_BRIDGE_API_KEY/ST_API_KEY).")

    user_prompt = (
        f"{prompt}\n\n"
        f"Page context (surrounding text):\n{page_context[:2000]}"
    )

    for attempt in range(1, max_retries + 1):
        timestamp = int(time.time())
        nonce = random.randint(0, 999999)
        token = generate_token(timestamp, nonce)

        headers = {
            "Content-Type": "application/json",
            "stchatgpt-auth-token": token,
            "stchatgpt-auth-nonce": str(nonce),
        }

        payload = {
            "version": 1,
            "clientAppName": CLIENT_APP_NAME,
            "service": CHAT_SERVICE,
            "timestamp": timestamp,
            "temperature": 0.2,
            "maxResponseTokens": 1024,
            "responseFormat": "text",
            "persona": DEFAULT_PERSONA,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "content": user_prompt},
                        {"type": "image", "content": data_url},
                    ],
                },
            ],
        }

        try:
            resp = requests.post(
                API_URL,
                json=payload,
                headers=headers,
                verify=False,
                timeout=timeout,
                proxies=PROXIES if use_proxy else None,
            )

            if resp.status_code >= 400:
                print(f"    [Attempt {attempt}] HTTP {resp.status_code}: {resp.text[:200]}")
                if attempt < max_retries:
                    time.sleep(2 ** attempt)
                    continue
                return ""

            data = resp.json()

            error_code = data.get("errorCode")
            if error_code not in (None, 0):
                msg = data.get("message", "")
                print(f"    [Attempt {attempt}] API error {error_code}: {msg[:200]}")
                if attempt < max_retries:
                    time.sleep(2 ** attempt)
                    continue
                return ""

            text = extract_text_from_response(data)
            return text or ""

        except Exception as exc:
            print(f"    [Attempt {attempt}] Error: {exc}")
            if attempt < max_retries:
                time.sleep(2 ** attempt)
                continue
            return ""

    return ""


def load_descriptions() -> dict[str, str]:
    """Load existing descriptions from the JSON file."""
    if not DESCRIPTIONS_FILE.exists():
        return {}
    try:
        data = json.loads(DESCRIPTIONS_FILE.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return {str(k): str(v) for k, v in data.items() if isinstance(v, str)}
    except Exception as exc:
        print(f"[WARN] Cannot load existing descriptions: {exc}")
    return {}


def save_descriptions(descriptions: dict[str, str]) -> None:
    """Save descriptions to the JSON file."""
    DESCRIPTIONS_FILE.write_text(
        json.dumps(descriptions, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def find_task_files(repo_filter: str | None = None) -> list[Path]:
    """Find all pdf_image_tasks_*.jsonl files in data/."""
    pattern = f"pdf_image_tasks_{repo_filter.lower()}.jsonl" if repo_filter else "pdf_image_tasks_*.jsonl"
    files = sorted(DATA_DIR.glob(pattern))
    return files


def load_tasks_from_file(task_file: Path) -> list[dict[str, Any]]:
    """Load tasks from a JSONL file."""
    tasks = []
    for line in task_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            tasks.append(json.loads(line))
        except json.JSONDecodeError as exc:
            print(f"[WARN] Invalid JSON line in {task_file}: {exc}")
    return tasks


def main():
    """CLI entry point: load pending PDF figure tasks, describe them via Alfred, and save results.

    Loads any existing descriptions so re-runs are incremental (skips figures
    already described unless ``--force``), processes tasks from all matching
    ``pdf_image_tasks_*.jsonl`` files, and periodically saves progress every 10
    figures in case of interruption.
    """
    parser = argparse.ArgumentParser(description="Enrich PDF figures with Alfred Vision descriptions")
    parser.add_argument("--repo", type=str, default=None, help="Filter by repo name (e.g. STM32CubeH7)")
    parser.add_argument("--max-figures", type=int, default=None, help="Max figures to process")
    parser.add_argument("--use-proxy", action="store_true", help="Use ST proxy")
    parser.add_argument("--delay", type=float, default=2.0, help="Delay between API calls (seconds)")
    parser.add_argument("--force", action="store_true", help="Re-describe already-described figures")
    args = parser.parse_args()

    # Load existing descriptions
    descriptions = load_descriptions()
    print(f"Existing descriptions: {len(descriptions)}")

    # Find task files
    task_files = find_task_files(args.repo)
    if not task_files:
        print(f"No task files found in {DATA_DIR} (pattern: pdf_image_tasks_*.jsonl)")
        print("Run the ingestion step first to generate PDF figure tasks.")
        return

    print(f"Task files found: {len(task_files)}")
    for tf in task_files:
        print(f"  - {tf.name}")

    # Collect all tasks
    all_tasks: list[dict[str, Any]] = []
    for tf in task_files:
        tasks = load_tasks_from_file(tf)
        all_tasks.extend(tasks)

    print(f"Total figure tasks: {len(all_tasks)}")

    # Filter already-described (unless --force)
    if not args.force:
        pending = [t for t in all_tasks if t.get("image_id", "") not in descriptions]
    else:
        pending = all_tasks

    print(f"Pending (not yet described): {len(pending)}")

    if args.max_figures:
        pending = pending[:args.max_figures]
        print(f"Limited to: {len(pending)} figures")

    if not pending:
        print("Nothing to do. All figures already have descriptions.")
        return

    # Process figures
    success_count = 0
    fail_count = 0

    for idx, task in enumerate(pending, start=1):
        figure_id = task.get("image_id", "unknown")
        image_path = Path(task.get("image_path", ""))
        prompt = task.get("prompt", "Describe this technical figure.")
        page_context = task.get("page_context_text", "")
        repo = task.get("repo", "?")
        page_num = task.get("page_number", "?")

        print(f"[{idx}/{len(pending)}] {repo} p{page_num} - {figure_id}")

        if not image_path.exists():
            print(f"    [SKIP] Image file not found: {image_path}")
            fail_count += 1
            continue

        try:
            data_url = load_image_as_data_url(image_path)
        except Exception as exc:
            print(f"    [SKIP] Cannot load image: {exc}")
            fail_count += 1
            continue

        description = call_alfred_for_figure(
            data_url=data_url,
            prompt=prompt,
            page_context=page_context,
            use_proxy=args.use_proxy,
        )

        if description:
            descriptions[figure_id] = description
            success_count += 1
            print(f"    -> {description[:80]}...")
        else:
            descriptions[figure_id] = "[FIGURE DESCRIPTION UNAVAILABLE]"
            fail_count += 1
            print(f"    -> FAILED")

        # Save progress every 10 figures
        if idx % 10 == 0:
            save_descriptions(descriptions)
            print(f"    [Saved progress: {idx}/{len(pending)}]")

        time.sleep(args.delay)

    # Final save
    save_descriptions(descriptions)

    print()
    print("=" * 60)
    print(f"Done! Processed: {success_count + fail_count}")
    print(f"  Success: {success_count}")
    print(f"  Failed:  {fail_count}")
    print(f"  Total descriptions in file: {len(descriptions)}")
    print(f"  Output: {DESCRIPTIONS_FILE}")
    print()
    print("Next step: re-run enrichment/delivery to inject descriptions into PDF text:")
    print("  python -m pipeline.enrichment.files_to_docs_v2")
    print("=" * 60)


if __name__ == "__main__":
    main()
